services:
  - type: web
    name: my-music-bot
    env: python
    buildCommand: |
      apt-get update -y && \
      apt-get install -y ffmpeg && \
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ASSISTANT_SESSION
        sync: false
